'use strict';

/* ═══════════════════════════════════════════════════════
   PETAL — Product Catalogue
   83 products across 4 categories: face, hair, body, fitness
═══════════════════════════════════════════════════════ */

const PI = 'images/pi/'; // product images base path

const products = [

  /* ── FACE ──────────────────────────────────────────── */
  {
    id: 1,
    name: 'LANEIGE Lip Sleeping Mask Berry 20g',
    brand: 'LANEIGE',
    category: 'face',
    price: 24,
    rating: 4.6,
    reviews: 36354,
    description: 'Overnight lip mask that transforms dry, flaky lips into a soft, pillowy pout.',
    tags: ['Best Seller', 'Under $25'],
    img: PI + 'laneige_lip_sleeping_mask_nourish_hydrate_vitamin_c_murumuru_shea_butter_antioxidants_flaky_dry_lips.png',
    link: 'https://amzn.to/4bmGuc9',
  },

  {
    id: 2,
    name: 'Hero Cosmetics Mighty Patch Original Pimple Patches',
    brand: 'Hero Cosmetics',
    category: 'face',
    price: 12.99,
    rating: 4.6,
    reviews: 182294,
    description: 'Hydrocolloid patches that shrink blemishes while you sleep — visibly clearer in hours.',
    tags: ['Best Seller', 'Under $25'],
    img: PI + 'mighty_patch_original_patch_from_hero_cosmetics_-_1_hydrocolloid_acne_pimple_patches_for_face_shrinking_zits_whiteheads_.png',
    link: 'https://amzn.to/3PDPqRG',
  },

  {
    id: 3,
    name: 'Paula\'s Choice SKIN PERFECTING 2% BHA Liquid Exfoliant',
    brand: 'Paula\'s Choice',
    category: 'face',
    price: 37,
    rating: 4.5,
    reviews: 113439,
    description: 'Cult-status BHA exfoliant that unclogs pores, smooths texture, and fades dark spots.',
    tags: ['Trending'],
    img: PI + 'paulas_choice_skin_perfecting_2_bha_liquid_exfoliant_with_salicylic_acid_facial_polish_for_enlarged_pores_wrinkles_fine_.png',
    link: 'https://amzn.to/4cQ5slk',
  },

  {
    id: 4,
    name: 'Drunk Elephant B-Hydra Intensive Hydration Serum',
    brand: 'Drunk Elephant',
    category: 'face',
    price: 54,
    rating: 4.5,
    reviews: 2447,
    description: 'Lightweight hydration serum that quenches thirsty skin with pro-vitamin B5 and pineapple ceramide.',
    tags: [],
    img: PI + 'b_hydra_intensive_hydration_serum_by_drunk_elephant_for_women_169_oz_serum.png',
    link: 'https://amzn.to/4sKIaSl',
  },

  {
    id: 5,
    name: 'TATCHA The Water Cream Oil-Free Moisturizer',
    brand: 'TATCHA',
    category: 'face',
    price: 74,
    rating: 4.6,
    reviews: 3947,
    description: 'Weightless Japanese water gel that melts in, hydrates deeply, and leaves skin poreless.',
    tags: ['Trending'],
    img: PI + 'tatcha_the_water_cream_cream_moisturizer_for_face_optimal_hydration_for_pure_poreless_skin.png',
    link: 'https://amzn.to/47P7xua',
  },

  {
    id: 6,
    name: 'BIODANCE Bio-Collagen Real Deep Mask',
    brand: 'BIODANCE',
    category: 'face',
    price: 19,
    rating: 4.5,
    reviews: 38315,
    description: 'Overnight collagen hydrogel mask that firms, plumps, and minimises pores while you sleep.',
    tags: ['Under $25'],
    img: PI + 'biodance_bio-collagen_real_deep_mask_hydrating_overnight_hydrogel_face_mask_pore_minimizing_elasticity_plumping_improvem.png',
    link: 'https://amzn.to/4btUoaY',
  },

  {
    id: 7,
    name: 'Summer Fridays Lip Butter Balm',
    brand: 'Summer Fridays',
    category: 'face',
    price: 24,
    rating: 4.7,
    reviews: 8806,
    description: 'Whipped lip balm that feels like butter and delivers instant, long-lasting moisture and shine.',
    tags: ['Trending', 'Under $25'],
    img: PI + 'summer_fridays_lip_butter_balm_-_conditioning_lip_mask_and_lip_balm_for_instant_moisture_shine_and_hydration_-_sheer-tin.png',
    link: 'https://amzn.to/4bLKNh6',
  },

  {
    id: 8,
    name: 'Rare Beauty Soft Pinch Liquid Blush',
    brand: 'Rare Beauty',
    category: 'face',
    price: 25,
    rating: 4.5,
    reviews: 4104,
    description: 'Blendable liquid blush with a natural, flushed finish that lasts all day with one drop.',
    tags: ['Best Seller'],
    img: PI + 'rare_beauty_soft_pinch_cheek_lip_trio_-_matte_blush_mini_liquid_blush_and_mini_tinted_lip_oil.png',
    link: 'https://amzn.to/4skLpjQ',
  },

  {
    id: 9,
    name: 'e.l.f. Halo Glow Liquid Filter',
    brand: 'e.l.f. Cosmetics',
    category: 'face',
    price: 15,
    rating: 4.5,
    reviews: 19131,
    description: 'Complexion booster that blurs imperfections and delivers a luminous, filtered-skin effect.',
    tags: ['Under $25'],
    img: PI + 'e.l.f._halo_glow_liquid_filter_complexion_booster_for_a_glowing_soft-focus_look_infused_with_hyaluronic_acid_vegan_cruel.png',
    link: 'https://amzn.to/4badgNq',
  },

  {
    id: 10,
    name: 'Charlotte Tilbury Pillow Talk Lip Liner',
    brand: 'Charlotte Tilbury',
    category: 'face',
    price: 28,
    rating: 4.4,
    reviews: 784,
    description: 'The universally flattering nude-pink lip liner that makes every lip look fuller and defined.',
    tags: ['Best Seller'],
    img: PI + 'charlotte_tilbury_lip_cheat_lip_liner_pencil_-_gives_lips_a_fuller-looking_defined_pout_-_enriched_with_jojoba_oil_hyalu.png',
    link: 'https://amzn.to/47nG2If',
  },

  {
    id: 11,
    name: 'FENTY BEAUTY Pro Filt\'r Soft Matte Foundation',
    brand: 'FENTY BEAUTY',
    category: 'face',
    price: 40,
    rating: 4.5,
    reviews: 2099,
    description: '50-shade longwear foundation with a soft-matte finish that photographs beautifully all day.',
    tags: ['Best Seller'],
    img: PI + 'fenty_beauty_by_rihanna_pro_filtr_soft_matte_longwear_liquid_foundation_190.png',
    link: 'https://amzn.to/3N6rEgB',
  },

  {
    id: 12,
    name: 'Glow Recipe Watermelon Glow Sleeping Mask',
    brand: 'Glow Recipe',
    category: 'face',
    price: 21,
    rating: 4.5,
    reviews: 1767,
    description: 'Overnight AHA mask with watermelon extract that reveals visibly brighter, smoother skin by morning.',
    tags: ['Trending', 'Under $25'],
    img: PI + 'glowrecipe.png',
    link: 'https://amzn.to/4sLPs8v',
  },

  {
    id: 13,
    name: 'TATCHA The Dewy Skin Cream',
    brand: 'TATCHA',
    category: 'face',
    price: 74,
    rating: 4.6,
    reviews: 5510,
    description: 'Rich plumping cream with Japanese botanicals that delivers an all-day dewy, glass-skin glow.',
    tags: ['Trending'],
    img: PI + 'tatcha_the_dewy_skin_cream_rich_face_cream_to_hydrate_plump_and_protect_dry_and_combo_skin.png',
    link: 'https://amzn.to/4cQUBHF',
  },

  {
    id: 14,
    name: 'Drunk Elephant Lala Retro Whipped Moisturizer',
    brand: 'Drunk Elephant',
    category: 'face',
    price: 66,
    rating: 4.3,
    reviews: 1864,
    description: 'Ceramide-rich whipped moisturizer that deeply nourishes and strengthens the skin barrier.',
    tags: ['Best Seller'],
    img: PI + 'drunk_elephant_lala_retro_whipped_cream_-_ceramide_moisturizer_-_clean_clinical_skincare_-_cruelty-free_-_dermatologist-.png',
    link: 'https://amzn.to/3NrQxTZ',
  },

  {
    id: 15,
    name: 'Peach & Lily Glass Skin Refining Serum',
    brand: 'Peach & Lily',
    category: 'face',
    price: 39,
    rating: 4.5,
    reviews: 802,
    description: 'Hydrating serum packed with niacinamide and peach extract for poreless, glass-like skin.',
    tags: [],
    img: PI + 'peach_lily_-_glass_skin_refining_serum_for_face_1.35_ounces_-_hyaluronic_acid_niacinamide_serum_-_sensitive_skin_-_vitam.png',
    link: 'https://amzn.to/4s72Eou',
  },

  {
    id: 16,
    name: 'Starface Hydro-Stars Pimple Patches Party Pack',
    brand: 'Starface',
    category: 'face',
    price: 26.99,
    rating: 4.6,
    reviews: 1615,
    description: 'Star-shaped hydrocolloid patches that make fighting breakouts fun and effective overnight.',
    tags: [],
    img: PI + 'starface_hydro-star_party_pack_pimple_patches_big_pack_hydrocolloid_clinically_proven_spot_shrinking_in_6_hours_absorb_f.png',
    link: 'https://amzn.to/46ZAfsa',
  },

  {
    id: 17,
    name: 'The Ordinary Niacinamide 10% + Zinc 1% Serum',
    brand: 'The Ordinary',
    category: 'face',
    price: 6,
    rating: 4.7,
    reviews: 51090,
    description: 'High-strength niacinamide serum that visibly reduces blemishes, pores, and shine.',
    tags: ['Best Seller', 'Under $25'],
    img: PI + 'the_ordinary_niacinamide_10_zinc_1_smoothing_serum_for_blemish_prone_skin.png',
    link: 'https://amzn.to/4dnzjS3',
  },

  {
    id: 18,
    name: 'Sunday Riley Good Genes All-In-One Lactic Acid',
    brand: 'Sunday Riley',
    category: 'face',
    price: 85,
    rating: 4.6,
    reviews: 3180,
    description: 'Lactic acid treatment that resurfaces, plumps, and brightens for younger-looking skin fast.',
    tags: [],
    img: PI + 'sunday_riley_good_genes_all-in-one_lactic_acid_treatment_face_serum.png',
    link: 'https://amzn.to/4bxjHZV',
  },

  {
    id: 19,
    name: 'Charlotte Tilbury Magic Cream Moisturizer',
    brand: 'Charlotte Tilbury',
    category: 'face',
    price: 69,
    rating: 4.5,
    reviews: 573,
    description: 'Legendary multi-tasking cream that primes, plumps, and hydrates for a flawless makeup base.',
    tags: ['Trending'],
    img: PI + 'charlotte_tilbury_magic_cream_face_moisturizer_-_firming_hydrating_face_cream_to_create_a_smoother-looking_base_for_make.png',
    link: 'https://amzn.to/4bqM23P',
  },

  {
    id: 20,
    name: 'Anastasia Beverly Hills Brow Wiz Pencil',
    brand: 'Anastasia Beverly Hills',
    category: 'face',
    price: 26,
    rating: 4.5,
    reviews: 26831,
    description: 'Ultra-fine brow pencil for hair-like strokes and naturally defined brows that last all day.',
    tags: ['Best Seller'],
    img: PI + 'browpencil.png',
    link: 'https://amzn.to/4rv9Ppz',
  },

  {
    id: 21,
    name: 'LANEIGE Water Bank Blue Hyaluronic Serum',
    brand: 'LANEIGE',
    category: 'face',
    price: 45,
    rating: 4.8,
    reviews: 681,
    description: 'Barrier-boosting hyaluronic serum that deeply hydrates and firms skin for a plump, radiant look.',
    tags: [],
    img: PI + 'laneige_water_bank_blue_hyaluronic_serum_hydrating_face_serum_with_peptide_green_tea_enzyme_to_improve_skin_firmness_rad.png',
    link: 'https://amzn.to/40zAO8f',
  },

  {
    id: 22,
    name: 'Benefit Gimme Brow+ Volumizing Eyebrow Gel',
    brand: 'Benefit Cosmetics',
    category: 'face',
    price: 26,
    rating: 4.5,
    reviews: 10514,
    description: 'Fiber-infused brow gel that builds instant volume and locks brows in a fluffy, full shape.',
    tags: [],
    img: PI + 'benefit_gimme_brow_volumizing_fiber_gel_3_medium_neutral_0.1_ounce.png',
    link: 'https://amzn.to/47nGB4P',
  },

  {
    id: 23,
    name: 'Too Faced Better Than Sex Mascara',
    brand: 'Too Faced',
    category: 'face',
    price: 29,
    rating: 4.4,
    reviews: 19926,
    description: 'Dramatic volumizing mascara that delivers inky black, clump-free lashes from the first coat.',
    tags: ['Best Seller'],
    img: PI + 'too_faced_better_than_sex_volumizing_mascara_dramatic_volume_length_cruelty_free.png',
    link: 'https://amzn.to/3PFfH1Z',
  },

  {
    id: 24,
    name: 'COSRX Advanced Snail 92 All in one Cream',
    brand: 'COSRX',
    category: 'face',
    price: 26,
    rating: 4.5,
    reviews: 59185,
    description: 'Lightweight snail mucin moisturiser that repairs the skin barrier and keeps skin soft and glowy.',
    tags: [],
    img: PI + 'cosrx_snail_mucin_92_face_moisturizer_352_oz_lightweight_moisturing_cream_for_soft_glowy_skin_korean_skin_care_korean_moisturizer_face_cream.png',
    link: 'https://amzn.to/4lurTid',
  },

  {
    id: 25,
    name: 'tarte Shape Tape Full Coverage Concealer',
    brand: 'tarte',
    category: 'face',
    price: 32,
    rating: 4.6,
    reviews: 15433,
    description: 'Full-coverage concealer with a matte finish that covers dark circles and blemishes all day.',
    tags: [],
    img: PI + 'tarte.png',
    link: 'https://amzn.to/4uyeo4S',
  },

  {
    id: 26,
    name: 'Tower 28 Beauty SOS Daily Rescue Facial Spray',
    brand: 'Tower 28 Beauty',
    category: 'face',
    price: 28,
    rating: 4.6,
    reviews: 4427,
    description: 'Hypochlorous acid facial spray that calms redness, soothes irritation, and sets makeup perfectly.',
    tags: [],
    img: PI + 'tower_28_sos_daily_rescue_facial_spray_-_hypochlorous_acid_spray_to_help_reduce_redness_calm_irritation_alleviate_flare-.png',
    link: 'https://amzn.to/4uwudcl',
  },

  {
    id: 27,
    name: 'Kosas Cloud Set Baked Setting Powder',
    brand: 'Kosas',
    category: 'face',
    price: 38,
    rating: 4.5,
    reviews: 440,
    description: 'Baked setting powder that blurs pores, sets makeup, and gives a natural skin-like finish.',
    tags: [],
    img: PI + 'kosas.png',
    link: 'https://amzn.to/4dwU3H7',
  },

  {
    id: 28,
    name: 'Byoma Moisturizing Rich Cream barrier',
    brand: 'Byoma',
    category: 'face',
    price: 15.99,
    rating: 4.4,
    reviews: 1990,
    description: 'Ceramide-packed barrier cream that strengthens and repairs skin with a rich, cozy texture.',
    tags: ['Trending', 'Under $25'],
    img: PI + 'byomarich.png',
    link: 'https://amzn.to/4cOQg7Z',
  },

  {
    id: 29,
    name: 'EltaMD UV Clear SPF 46 Sunscreen',
    brand: 'EltaMD',
    category: 'face',
    price: 45,
    rating: 4.5,
    reviews: 67369,
    description: 'Dermatologist-favourite zinc oxide sunscreen that protects and calms acne-prone and sensitive skin.',
    tags: [],
    img: PI + 'eltamd_uv_clear_face_sunscreen_spf_46_oil-free_sunscreen_with_zinc_oxide_dermatologist_recommended.png',
    link: 'https://amzn.to/4bAx2Rk',
  },

  {
    id: 30,
    name: 'La Roche-Posay Toleriane Double Repair Moisturizer',
    brand: 'La Roche-Posay',
    category: 'face',
    price: 24.99,
    rating: 4.6,
    reviews: 48031,
    description: 'Gentle ceramide moisturiser that restores the skin barrier and provides 48-hour hydration.',
    tags: ['Under $25'],
    img: PI + 'la_roche-posay_toleriane_double_repair_face_moisturizer_daily_moisturizer_face_cream_with_ceramide_niacinamide_for_all_s.png',
    link: 'https://amzn.to/4cQtcpf',
  },

  {
    id: 31,
    name: 'CeraVe Moisturizing Cream Body and Face',
    brand: 'CeraVe',
    category: 'face',
    price: 20.49,
    rating: 4.7,
    reviews: 142773,
    description: 'Fragrance-free moisturizer with ceramides and hyaluronic acid for dry to very dry skin.',
    tags: ['Under $25'],
    img: PI + 'cerave_moisturizing_cream_body_and_face_moisturizer_for_dry_skin_body_cream_with_hyaluronic_acid_and_ceramides_daily_moi.png',
    link: 'https://amzn.to/40yzVgo',
  },

  {
    id: 32,
    name: 'Dermalogica Daily Microfoliant Exfoliating Powder',
    brand: 'Dermalogica',
    category: 'face',
    price: 69,
    rating: 4.6,
    reviews: 12370,
    description: 'Rice enzyme powder exfoliant that polishes skin to a brighter, smoother, more even complexion.',
    tags: [],
    img: PI + 'dermalogica_daily_microfoliant_face_exfoliator_scrub_powder_with_salicylic_acid_and_papaya_enzyme_achieve_brighter_smoot.png',
    link: 'https://amzn.to/4dmK07s',
  },

  {
    id: 33,
    name: 'The INKEY List Retinol Serum',
    brand: 'The INKEY List',
    category: 'face',
    price: 11.2,
    rating: 4.5,
    reviews: 1891,
    description: 'Affordable retinol serum that visibly reduces fine lines, hyperpigmentation, and breakouts overnight.',
    tags: ['Under $25'],
    img: PI + 'the_inkey_list_starter_dual_retinol_serum_1_fl_oz_0.5_amisol_trio_0.2_symrelief_gentle_skin_renewal_smooths_fine_lines_h.png',
    link: 'https://amzn.to/4uxVc7A',
  },

  {
    id: 34,
    name: 'Augustinus Bader The Rich Cream',
    brand: 'Augustinus Bader',
    category: 'face',
    price: 315,
    rating: 4.4,
    reviews: 163,
    description: 'Luxury regenerating face cream with TFC8 technology for visibly firmer, younger-looking skin.',
    tags: ['Trending'],
    img: PI + 'augustinus_bader_the_rich_cream_luxury_face_cream_hydrating_and_nourishing_face_moisturizer_facial_moisturizer_for_wrinkle_reduction_and_cellular_rene.png',
    link: 'https://amzn.to/4sLAkIb',
  },

  /* ── BODY ──────────────────────────────────────────── */
  {
    id: 35,
    name: 'Sol de Janeiro Brazilian Bum Bum Body Cream',
    brand: 'Sol de Janeiro',
    category: 'body',
    price: 48,
    rating: 4.6,
    reviews: 54181,
    description: 'Iconic Brazilian body cream with cupuacu butter and guarana that leaves skin irresistibly soft.',
    tags: ['Trending'],
    img: PI + 'brazilian_bum_bum_cream.png',
    link: 'https://amzn.to/4ltNRlb',
  },

  {
    id: 36,
    name: 'Sol de Janeiro Cheirosa 62 Hair and Body Mist',
    brand: 'Sol de Janeiro',
    category: 'body',
    price: 25,
    rating: 4.7,
    reviews: 50662,
    description: 'Addictive pistachio and salted caramel fragrance mist for hair and body.',
    tags: ['Trending'],
    img: PI + 'sol_de_janeiro_hair_body_perfume_mist.png',
    link: 'https://amzn.to/47DgJSn',
  },

  {
    id: 37,
    name: 'SOL DE JANEIRO Visibly Brightening and Smoothing Bom Dia',
    brand: 'Sol de Janeiro',
    category: 'body',
    price: 48,
    rating: 4.7,
    reviews: 4690,
    description: 'AHA body cream that exfoliates and brightens for visibly smoother, more even-toned skin.',
    tags: [],
    img: PI + 'sol_de_janeiro_visibly_brightening_and_smoothing_bom_dia_aha_body_cream.png',
    link: 'https://amzn.to/3PEwWQZ',
  },

  {
    id: 38,
    name: 'Tree Hut Shea Sugar Scrub Moroccan Rose',
    brand: 'Tree Hut',
    category: 'body',
    price: 10.99,
    rating: 4.8,
    reviews: 151452,
    description: 'Bestselling shea sugar scrub that exfoliates and deeply moisturises for silky-smooth skin.',
    tags: ['Under $25'],
    img: PI + 'tree_hut_moroccan_rose_shea_sugar_scrub_exfoliating_hydrating_body_scrub_with_shea_butter_essential_oils_smooth_soften_skin_18_oz.png',
    link: 'https://amzn.to/3PnCIGB',
  },

  {
    id: 39,
    name: 'eos Shea Better Body Lotion Vanilla Cashmere',
    brand: 'eos',
    category: 'body',
    price: 10.99,
    rating: 4.7,
    reviews: 66579,
    description: 'Fast-absorbing shea lotion that provides 24-hour moisture without any greasy residue.',
    tags: ['Under $25'],
    img: PI + 'eos_shea_better_body_lotion_vanilla_cashmere_24-hour_moisture_skin_care_lightweight_non-greasy_natural_shea_vegan_vanill.png',
    link: 'https://amzn.to/4uwv4d3',
  },

  {
    id: 40,
    name: 'Kopari Beauty Coconut Body Glow Oil',
    brand: 'Kopari Beauty',
    category: 'body',
    price: 39,
    rating: 4.5,
    reviews: 276,
    description: 'Shimmery coconut body oil with hyaluronic acid that hydrates and leaves skin glowing all day.',
    tags: [],
    img: PI + 'kopari_golden_aura_body_oil_with_24k_gold_hyaluronic_acid_-_hydrating_formula_for_glowing_skin_3.3_oz.png',
    link: 'https://amzn.to/4bLn28T',
  },

  {
    id: 41,
    name: 'Slip Pure Silk Pillowcase Queen Pink/Silver',
    brand: 'Slip',
    category: 'body',
    price: 120,
    rating: 4.5,
    reviews: 1667,
    description: '100% mulberry silk pillowcase that reduces hair breakage, frizz and sleep lines.',
    tags: ['Trending'],
    img: PI + 'slip_the_original_queen_silk_pillow_cases_-_100_pure_22_momme_mulberry_silk_pillowcase_for_hair_and_skin_-_queen_standar.png',
    link: 'https://amzn.to/4sMgv3q',
  },

  {
    id: 42,
    name: 'Elemis Pro-Collagen Marine Cream',
    brand: 'Elemis',
    category: 'body',
    price: 145,
    rating: 4.6,
    reviews: 1881,
    description: 'Award-winning anti-ageing marine cream that visibly reduces wrinkles and firms skin in 15 days.',
    tags: [],
    img: PI + 'elemis_pro_collagen_marine_cream_spf_30_lightweight_anti_wrinkle_daily_facial_moisturizer.png',
    link: 'https://amzn.to/4doosHy',
  },

  {
    id: 43,
    name: 'Nutrafol Women Hair Growth Supplement',
    brand: 'Nutrafol',
    category: 'body',
    price: 88,
    rating: 4.1,
    reviews: 15617,
    description: 'Clinically proven hair growth supplement with botanicals for visibly thicker, fuller hair.',
    tags: [],
    img: PI + 'nutrafol_womens_balance_hair_growth_supplements_ages_45_and_up_clinically_proven_for_visibly_thicker_hair_and_scalp_cove.png',
    link: 'https://amzn.to/4btzsAS',
  },

  {
    id: 44,
    name: 'Youth To The People Superfood Air-Whip Moisturizer',
    brand: 'Youth To The People',
    category: 'body',
    price: 49,
    rating: 4.6,
    reviews: 2684,
    description: 'Whipped superfood moisturiser with kale and hyaluronic acid for an all-day dewy glow.',
    tags: [],
    img: PI + 'youth.png',
    link: 'https://amzn.to/3P8y8w0',
  },

  /* ── HAIR ──────────────────────────────────────────── */
  {
    id: 45,
    name: 'Olaplex No.3 Hair Perfector Treatment',
    brand: 'Olaplex',
    category: 'hair',
    price: 34,
    rating: 4.6,
    reviews: 141617,
    description: 'At-home bond-building treatment that repairs damage and strengthens hair from within.',
    tags: ['Best Seller'],
    img: PI + 'olaplex_n.3plus_complete_repair_treatment_3-minute_pre-shampoo_treatment_to_immediately_repair_hair_damage_for_softer_st.png',
    link: 'https://amzn.to/46Z8UWX',
  },

  {
    id: 46,
    name: 'Olaplex No.7 Bonding Oil Heat Protectant',
    brand: 'Olaplex',
    category: 'hair',
    price: 32,
    rating: 4.7,
    reviews: 59315,
    description: 'Highly concentrated bonding oil that adds shine, reduces frizz, and protects against heat styling.',
    tags: ['Best Seller'],
    img: PI + 'olaplex7.png',
    link: 'https://amzn.to/4bucauJ',
  },

  {
    id: 47,
    name: 'Mielle Organics Rosemary Mint Scalp and Hair Oil',
    brand: 'Mielle Organics',
    category: 'hair',
    price: 9.99,
    rating: 4.5,
    reviews: 122592,
    description: 'Rosemary and biotin oil that nourishes the scalp and supports stronger, healthier hair growth.',
    tags: ['Under $25'],
    img: PI + 'mielle_organics_rosemary_mint_hair_oil_strengthening_biotin_oil_infused_frizzy_damaged_hair_care_split_ends_dry_scalp_treatment_to_support_longer_heal.png',
    link: 'https://amzn.to/4cLjRPB',
  },

  {
    id: 48,
    name: 'OUAI Leave In Conditioner and Heat Protectant Spray',
    brand: 'OUAI',
    category: 'hair',
    price: 32,
    rating: 4.6,
    reviews: 14053,
    description: 'Multitasking leave-in spray that detangles, smooths frizz and protects hair from heat.',
    tags: [],
    img: PI + 'ouai_leave_in_conditioner_heat_protectant_for_hair_prep_hair_for_styling_or_use_as_detangling_spray_to_fight_frizz_flyaways_no_parabens_sulfates_or_ph.png',
    link: 'https://amzn.to/4sNBfrG',
  },

  {
    id: 49,
    name: 'Bumble and bumble Hairdresser\'s Invisible Oil',
    brand: 'Bumble and bumble',
    category: 'hair',
    price: 34,
    rating: 4.7,
    reviews: 5826,
    description: 'Weightless six-oil blend that primes, protects, and gives hair runway-ready shine and softness.',
    tags: [],
    img: PI + 'bumble_and_bumble._hairdressers_invisible_oil_heat_uv_protection_leave-in_conditioner_hair_primer_hydrating_anti_frizz_c.png',
    link: 'https://amzn.to/4uvvbpd',
  },

  {
    id: 50,
    name: 'K18 Leave-In Molecular Repair Hair Mask',
    brand: 'K18',
    category: 'hair',
    price: 29,
    rating: 4.3,
    reviews: 28105,
    description: 'Patented peptide leave-in mask that repairs damage in 4 minutes without rinsing.',
    tags: ['Best Seller'],
    img: PI + 'k18_leave-in_molecular_repair_hair_mask_patented_lasting_repair_for_dry_frizzy_damaged_hair_reverse_damage_in_4_minutes_.png',
    link: 'https://amzn.to/4bLKGSD',
  },

  {
    id: 51,
    name: 'Amika The Kure Bond Repair Shampoo',
    brand: 'amika',
    category: 'hair',
    price: 29,
    rating: 4.7,
    reviews: 2724,
    description: 'Strengthening shampoo that repairs bond damage from heat, color, and chemical treatments.',
    tags: [],
    img: PI + 'amika_the_kure_strength_repair_shampoo_275ml.png',
    link: 'https://amzn.to/4bnvKc4',
  },

  {
    id: 52,
    name: 'COLOR WOW Dream Coat Supernatural Spray',
    brand: 'COLOR WOW',
    category: 'hair',
    price: 30,
    rating: 4.3,
    reviews: 95904,
    description: 'Award-winning anti-humidity spray that banishes frizz and locks in sleek, shiny hair for days.',
    tags: [],
    img: PI + 'color_wow_dream_coat_anti_humidity_treatment_spray_anti_frizz_hair_smoothing_spray_with_built_in_heat_protectant_award_winning_leave_in_treatment_for_.png',
    link: 'https://amzn.to/3Pf5clW',
  },

  {
    id: 53,
    name: 'Gisou Honey Infused Hair Oil',
    brand: 'Gisou',
    category: 'hair',
    price: 44,
    rating: 4.6,
    reviews: 1070,
    description: 'Honey-infused hair oil that adds luminous shine, tames frizz, and nourishes every strand.',
    tags: ['Trending'],
    img: PI + 'gisou_honey_infused_hair_oil_-_hydrating_frizz_control_treatment_with_mirsalehi_honey_adds_shine_heat_protectant_for_all.png',
    link: 'https://amzn.to/4uyt8Rl',
  },

  {
    id: 54,
    name: 'Drybar Buttercup Blow-Dryer',
    brand: 'Drybar',
    category: 'hair',
    price: 199,
    rating: 4.4,
    reviews: 1074,
    description: 'Powerful professional blow-dryer that delivers salon-quality speed, smoothness, and shine at home.',
    tags: [],
    img: PI + 'drybar_buttercup_blow_dryer_faster_drying_more_shine_less_frizz_ultra_powerful_yet_lightweight_professional_hair_dryer.png',
    link: 'https://amzn.to/4rA0ixg',
  },

  {
    id: 55,
    name: 'Kitsch Satin Scrunchies Set Neutrals',
    brand: 'Kitsch',
    category: 'hair',
    price: 9.99,
    rating: 4.6,
    reviews: 50198,
    description: 'Frizz-free satin scrunchies that are gentler on hair — no creases, no breakage.',
    tags: ['Under $25'],
    img: PI + 'kitsch_ultra-petite_satin_scrunchies_for_women_-_no_crease_frizz-free_sleep_softer_than_silk_scrunchies_gentle_on_hair_s.png',
    link: 'https://amzn.to/4s7ZQHL',
  },

  {
    id: 56,
    name: 'Malin + Goetz Peppermint Shampoo',
    brand: 'Malin + Goetz',
    category: 'hair',
    price: 28,
    rating: 4.3,
    reviews: 1988,
    description: 'Gentle clarifying shampoo with peppermint that cleanses the scalp and leaves hair refreshed.',
    tags: [],
    img: PI + 'malin_goetz_shampoo_hydrating_basil_or_clarifying_peppermint_formula_daily_cleanser_with_amino_acids_for_all_hair_types_.png',
    link: 'https://amzn.to/4bLKUZZ',
  },

  /* ── FACE ──────────────────────────────────────────── */
  {
    id: 57,
    name: 'PLANTIFIQUE Stainless Steel Gua Sha',
    brand: 'PLANTIFIQUE',
    category: 'face',
    price: 15.95,
    rating: 4.5,
    reviews: 18194,
    description: 'Stainless steel gua sha tool that depuffs, sculpts, and boosts circulation for a lifted look.',
    tags: ['Under $25'],
    img: PI + 'guasha.png',
    link: 'https://amzn.to/4soQirO',
  },

  {
    id: 58,
    name: 'Medicube Age-R Booster Pro Korean Device',
    brand: 'Medicube',
    category: 'face',
    price: 220,
    rating: 4.3,
    reviews: 3500,
    description: '6-in-1 Korean skincare device that boosts serum absorption and targets pores for glass skin.',
    tags: ['Trending'],
    img: PI + 'medicube_booster_pro_6-in-1_real_glass_glow_beauty_massager_for_clear_radiant_firmer-looking_skin_korean_skin_care_pink.png',
    link: 'https://amzn.to/4ltPfnT',
  },

  /* ── FITNESS ──────────────────────────────────────────── */
  {
    id: 59,
    name: 'Under Armour Unisex-Adult Undeniable 5.0 Duffle',
    brand: 'Under Armour',
    category: 'fitness',
    price: 45,
    rating: 4.7,
    reviews: 10819,
    description: 'Durable, water-resistant gym duffle with wet/dry separation pocket and adjustable strap.',
    tags: [],
    img: PI + 'underamour.png',
    link: 'https://amzn.to/4uE50wO',
  },

  {
    id: 60,
    name: 'Stanley Quencher H2.0 FlowState Tumbler 40oz',
    brand: 'Stanley',
    category: 'fitness',
    price: 45,
    rating: 4.7,
    reviews: 88624,
    description: 'The viral insulated tumbler with a rotating lid that keeps drinks cold all day — anywhere.',
    tags: ['Trending'],
    img: PI + 'stanley_quencher_h2.0_tumbler_with_handle_and_straw_40_oz_flowstate_3-position_lid_cup_holder_compatible_for_travel_insu_2.png',
    link: 'https://amzn.to/4bHRPn3',
  },

  {
    id: 61,
    name: 'Manduka PRO Yoga Mat 6mm',
    brand: 'Manduka',
    category: 'fitness',
    price: 144,
    rating: 4.4,
    reviews: 935,
    description: 'Premium lifetime-guarantee yoga mat with unmatched cushion and a closed-cell non-slip surface.',
    tags: [],
    img: PI + 'mat.png',
    link: 'https://amzn.to/4lDg7lm',
  },

  {
    id: 62,
    name: 'Bala Bangles Wrist and Ankle Weights 1lb',
    brand: 'Bala',
    category: 'fitness',
    price: 55,
    rating: 4.6,
    reviews: 629,
    description: 'Adjustable silicone wrist and ankle weights that add resistance to any workout beautifully.',
    tags: [],
    img: PI + 'bala_bangles_wrist_ankle_weights_-_adjustable_weighted_bands_for_women_men_-_soft_silicone_arm_leg_weights_for_pilates_y.png',
    link: 'https://amzn.to/4btHtGf',
  },

  {
    id: 63,
    name: 'Theragun Mini Percussive Therapy Device',
    brand: 'Therabody',
    category: 'fitness',
    price: 159.99,
    rating: 4.6,
    reviews: 2365,
    description: 'Pocket-sized percussion massager that relieves muscle soreness and tension in seconds.',
    tags: [],
    img: PI + 'theragun_mini_3rd_generation_by_therabody_ultra-portable_massage_gun_and_travel_essential_for_fast_effective_pain_and_te.png',
    link: 'https://amzn.to/4rC8KMK',
  },

  {
    id: 64,
    name: 'Hydro Flask Wide Mouth Water Bottle 32oz',
    brand: 'Hydro Flask',
    category: 'fitness',
    price: 44.95,
    rating: 4.7,
    reviews: 29775,
    description: 'Insulated stainless steel water bottle that keeps drinks ice-cold for 24 hours — leak-proof.',
    tags: [],
    img: PI + 'hydro_flask_water_bottle_-_insulated_stainless_steel_-_wide_mouth_flex_lid_non_spill_leakproof_and_refillable_in_32_oz_w.png',
    link: 'https://amzn.to/4sRg2NC',
  },

  /* ── BODY ──────────────────────────────────────────── */
  {
    id: 65,
    name: 'OUAI Body Cream, Melrose Place',
    brand: 'OUAI',
    category: 'body',
    price: 40,
    rating: 4.6,
    reviews: 2730,
    description: 'Rich body cream with shea butter and ceramides that melts into skin for long-lasting moisture.',
    tags: ['Trending'],
    img: PI + 'ouai.png',
    link: 'https://amzn.to/4bmr7jW',
  },

  /* ── FACE ──────────────────────────────────────────── */
  {
    id: 66,
    name: 'Dr.Althea 345 Relief Cream',
    brand: 'Dr.Althea',
    category: 'face',
    price: 27,
    rating: 4.6,
    reviews: 13874,
    description: 'Skin barrier relief cream with Centella Asiatica that soothes redness and calms irritation.',
    tags: ['Trending'],
    img: PI + '365.png',
    link: 'https://amzn.to/4dvxDWM',
  },

  /* ── FITNESS ──────────────────────────────────────────── */
  {
    id: 67,
    name: 'RingConn Gen 2, World’s First Smart Ring with Sleep Apnea Monitoring',
    brand: 'RingConn',
    category: 'fitness',
    price: 299,
    rating: 4.2,
    reviews: 4917,
    description: 'RingConn Gen 2, World’s First Smart Ring with Sleep Apnea Monitoring — a trending beauty pick curated from Pinterest.',
    tags: [],
    img: PI + 'ring.png',
    link: 'https://amzn.to/3NrQ0l2',
  },

  /* ── FACE ──────────────────────────────────────────── */
  {
    id: 68,
    name: 'The INKEY List Retinol Eye Cream',
    brand: 'The INKEY List',
    category: 'face',
    price: 14,
    rating: 4.7,
    reviews: 78,
    description: 'Retinol and caffeine eye cream that visibly reduces dark circles, puffiness, and fine lines.',
    tags: ['Under $25'],
    img: PI + 'the_inkey_list_retinol_serum_1_fl_oz_reduces_hyperpigmentation_anti-ageing_skincare_acne_treatment_vegan_friendly_suitab.png',
    link: 'https://amzn.to/4bq0ol5',
  },

  {
    id: 69,
    name: 'Rare Beauty Warm Wishes Powder Bronzer',
    brand: 'Rare Beauty',
    category: 'face',
    price: 36,
    rating: 4.7,
    reviews: 35,
    description: 'Silky bronzer with a sun-kissed, natural finish that adds warmth and dimension to any complexion.',
    tags: ['Best Seller'],
    img: PI + 'rare_beauty_soft_pinch_cheek_lip_trio_-_matte_blush_mini_liquid_blush_and_mini_tinted_lip_oil.png',
    link: 'https://amzn.to/4brFC4q',
  },

  /* ── BODY ──────────────────────────────────────────── */
  {
    id: 70,
    name: 'Sol de Janeiro Jet Set',
    brand: 'Sol de Janeiro',
    category: 'body',
    price: 34,
    rating: 4.7,
    reviews: 17935,
    description: 'Iconic Sol de Janeiro travel set featuring best-selling scented body care favorites.',
    tags: [],
    img: PI + 'solset.png',
    link: 'https://amzn.to/4bxK3el',
  },

  /* ── FACE ──────────────────────────────────────────── */
  {
    id: 71,
    name: 'Laneige Lip Glowy Balm Gummy Bear',
    brand: 'LANEIGE',
    category: 'face',
    price: 19,
    rating: 4.7,
    reviews: 35450,
    description: 'Sheer tinted lip balm with shea butter that delivers a glossy, hydrated pout all day.',
    tags: ['Under $25'],
    img: PI + 'laneige_lip_glowy_balm_sheer_tinted_lip_moisturizer_with_shea_butter_for_hydrating_shine_soft_lips.png',
    link: 'https://amzn.to/4lwtpQA',
  },

  {
    id: 72,
    name: 'Summer Fridays Dream Lip Oil',
    brand: 'Summer Fridays',
    category: 'face',
    price: 24,
    rating: 4.7,
    reviews: 8806,
    description: 'Nourishing lip oil that plumps, conditions, and adds a glossy sheer tint for irresistible lips.',
    tags: ['Under $25'],
    img: PI + 'summer_fridays_tinted_lip_butter_balm_-_conditioning_vegan_lip_balm_for_instant_moisture_shine_hydration_-_sheer-tinted_.png',
    link: 'https://amzn.to/4rvlrZt',
  },

  {
    id: 73,
    name: 'ILIA - Multi-Stick For Lips + Cheeks',
    brand: 'ILIA',
    category: 'face',
    price: 36,
    rating: 4.5,
    reviews: 3331,
    description: 'Versatile clean beauty stick that adds a natural flush of color to cheeks and lips in one swipe.',
    tags: ['Trending'],
    img: PI + 'ilia.png',
    link: 'https://amzn.to/40CiZph',
  },

  {
    id: 74,
    name: 'Byoma Moisturizing Gel-Cream barrier skincare',
    brand: 'Byoma',
    category: 'face',
    price: 14.99,
    rating: 4.4,
    reviews: 4406,
    description: 'Lightweight gel-cream with ceramide complex that restores the skin barrier and locks in moisture.',
    tags: ['Trending', 'Under $25'],
    img: PI + 'byoma_moisturizing_gel_cream_-_barrier_repair_cream_gel_face_lotion_with_niacinamide_and_green_tea_-_ceramide_face_moist.png',
    link: 'https://amzn.to/3N8WO70',
  },

  /* ── HAIR ──────────────────────────────────────────── */
  {
    id: 75,
    name: 'Mielle Organics Rosemary Mint Hair Mask',
    brand: 'Mielle Organics',
    category: 'hair',
    price: 9.99,
    rating: 4.5,
    reviews: 122592,
    description: 'Deep conditioning hair mask with rosemary and biotin that restores moisture and reduces breakage.',
    tags: ['Under $25'],
    img: PI + 'mielle_organics_rosemary_mint_hair_oil_strengthening_biotin_oil_infused_frizzy_damaged_hair_care_split_ends_dry_scalp_treatment_to_support_longer_heal.png',
    link: 'https://amzn.to/4sI5Kix',
  },

  {
    id: 76,
    name: 'Olaplex No.6 Bond Smoother Leave-In Styling',
    brand: 'Olaplex',
    category: 'hair',
    price: 34,
    rating: 4.6,
    reviews: 53836,
    description: 'Reparative leave-in styling cream that eliminates frizz and adds a glossy, smooth finish.',
    tags: ['Best Seller'],
    img: PI + 'olaplex6.png',
    link: 'https://amzn.to/4bT2nQc',
  },

  {
    id: 77,
    name: 'Nutrafol Women\'s Balance Hair Supplement',
    brand: 'Nutrafol',
    category: 'hair',
    price: 88,
    rating: 4.2,
    reviews: 18255,
    description: 'Clinically tested hair supplement formulated for women 45+ to support thicker, fuller hair growth.',
    tags: [],
    img: PI + 'nutrafol_womens_balance_hair_growth_supplements_ages_45_and_up_clinically_proven_for_visibly_thicker_hair_and_scalp_cove.png',
    link: 'https://amzn.to/4brGeae',
  },

  {
    id: 78,
    name: 'Olaplex Wash and Shine Hair Kit',
    brand: 'Olaplex',
    category: 'hair',
    price: 68,
    rating: 4.6,
    reviews: 4704,
    description: 'Complete Olaplex bond-repair kit for cleansing, conditioning and styling healthier, stronger hair.',
    tags: ['Trending'],
    img: PI + 'olaplexset.png',
    link: 'https://amzn.to/40FFt8Q',
  },

  /* ── FITNESS ──────────────────────────────────────────── */
  {
    id: 79,
    name: 'Retrospec Solana Yoga Mat 1" Thick w/Nylon Strap for Men & Women',
    brand: 'Retrospec',
    category: 'fitness',
    price: 39.99,
    rating: 4.6,
    reviews: 13975,
    description: 'Retrospec Solana Yoga Mat 1" Thick w/Nylon Strap for Men & Women — a trending beauty pick curated from Pinterest.',
    tags: [],
    img: PI + 'yogamatbl.png',
    imgPosition: 'center bottom',
    link: 'https://amzn.to/3NN8Kvh',
  },

  {
    id: 80,
    name: 'Bala Bangles 2lb Set Wrist Weights',
    brand: 'Bala',
    category: 'fitness',
    price: 65,
    rating: 4.6,
    reviews: 629,
    description: 'Heavier 2lb wrist weight set for building strength and resistance during barre and pilates.',
    tags: [],
    img: PI + 'bala2.png',
    link: 'https://amzn.to/3NcekHx',
  },

  {
    id: 81,
    name: 'WHOOP Body Fitness Tracker Strap',
    brand: 'WHOOP',
    category: 'fitness',
    price: 239,
    rating: 4.2,
    reviews: 2684,
    description: 'Replacement WHOOP strap for body-placement tracking — comfortable all-day and night wear.',
    tags: [],
    img: PI + 'whoop_40_with_12_month_subscription_wearable_health_fitness_activity_tracker_continuous_monitoring_performance_optimization_heart_rate_tracking_improv.png',
    link: 'https://amzn.to/47yPl80',
  },

  {
    id: 82,
    name: 'Theragun Relief Handheld Percussive Massager',
    brand: 'Theragun',
    category: 'fitness',
    price: 219.99,
    rating: 4.6,
    reviews: 193,
    description: 'Ergonomic handheld massager with QuietForce technology for deep muscle relief and recovery.',
    tags: [],
    img: PI + 'theragun_mini_3rd_generation_by_therabody_ultra-portable_massage_gun_and_travel_essential_for_fast_effective_pain_and_te.png',
    link: 'https://amzn.to/4doAf8S',
  },

  {
    id: 83,
    name: 'Stanley IceFlow Flip Straw Tumbler 30oz',
    brand: 'Stanley',
    category: 'fitness',
    price: 45,
    rating: 4.7,
    reviews: 13975,
    description: 'Sleek flip-straw tumbler that keeps water ice-cold and fits perfectly in any cup holder.',
    tags: ['Best Seller'],
    img: PI + 'stanley_quencher_h2.0_tumbler_with_handle_and_straw_40_oz_flowstate_3-position_lid_cup_holder_compatible_for_travel_insu.png',
    link: 'https://amzn.to/4beY2Xv',
  },

];

/* ── Helper functions ─────────────────────────────────── */
function getByCategory(cat) {
  return products.filter(p => p.category === cat);
}

function getByTag(tag) {
  return products.filter(p => p.tags.includes(tag));
}

function getBrandsForCategory(cat) {
  const pool = (cat === 'all') ? products : products.filter(p => p.category === cat);
  return [...new Set(pool.map(p => p.brand))].sort();
}

function getTrending()    { return getByTag('Trending'); }
function getBestSellers() { return getByTag('Best Seller'); }
function getUnder25()     {
  return products.filter(p =>
    p.tags.includes('Under $25') &&
    !p.tags.includes('Trending') &&
    !p.tags.includes('Best Seller')
  );
}
